"""Extra fields for mothers

Revision ID: 0d59fb754647
Revises: caaf822d6cdd
Create Date: 2026-01-03 15:29:31.077878

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0d59fb754647"
down_revision: Union[str, Sequence[str], None] = "caaf822d6cdd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("pregnant_women", sa.Column("pregnancy_stage", sa.String(length=20), nullable=True))
    op.add_column("pregnant_women", sa.Column("pregnancy_week", sa.Integer(), nullable=True))
    op.add_column("pregnant_women", sa.Column("expected_due_date", sa.Date(), nullable=True))
    op.add_column("pregnant_women", sa.Column("baby_date_of_birth", sa.Date(), nullable=True))
    op.add_column("pregnant_women", sa.Column("blood_type", sa.String(length=5), nullable=True))
    op.add_column("pregnant_women", sa.Column("allergies", sa.JSON(), nullable=True))
    op.add_column("pregnant_women", sa.Column("diet_preferences", sa.JSON(), nullable=True))
    op.add_column("pregnant_women", sa.Column("medical_conditions", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pregnant_women", "medical_conditions")
    op.drop_column("pregnant_women", "diet_preferences")
    op.drop_column("pregnant_women", "allergies")
    op.drop_column("pregnant_women", "blood_type")
    op.drop_column("pregnant_women", "baby_date_of_birth")
    op.drop_column("pregnant_women", "expected_due_date")
    op.drop_column("pregnant_women", "pregnancy_week")
    op.drop_column("pregnant_women", "pregnancy_stage")
    # ### end Alembic commands ###
