"""Added 'edu_article_categories' table, update relevant FK for edu_articles

Revision ID: 12350cae9e97
Revises: f19e156017a8
Create Date: 2026-01-09 01:59:39.491451

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "12350cae9e97"
down_revision: Union[str, Sequence[str], None] = "f19e156017a8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "edu_article_categories",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("label"),
    )
    op.add_column("edu_articles", sa.Column("category_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "edu_articles", "edu_article_categories", ["category_id"], ["id"])
    op.drop_column("edu_articles", "category")

    # Drop the enum type that is no longer needed
    op.execute("DROP TYPE IF EXISTS eduarticlecategory CASCADE;")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # This migration cannot be safely downgraded as it removes the enum type.
    # The enum would need to be recreated and the original column restored.
    # For now, we prevent downgrading by raising an exception.
    raise NotImplementedError("Downgrade not supported - the EduArticleCategory enum has been permanently removed.")
