"""Added 'edu_article_categories' table, update relevant FK for edu_articles

Revision ID: 12350cae9e97
Revises: f19e156017a8
Create Date: 2026-01-09 01:59:39.491451

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "12350cae9e97"
down_revision: Union[str, Sequence[str], None] = "f19e156017a8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "edu_article_categories",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("label", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("label"),
    )
    op.add_column("edu_articles", sa.Column("category_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "edu_articles", "edu_article_categories", ["category_id"], ["id"])
    op.drop_column("edu_articles", "category")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "edu_articles",
        sa.Column(
            "category",
            postgresql.ENUM(
                "NUTRITION",
                "BODY",
                "BABY",
                "FEEL_GOOD",
                "MEDICAL",
                "EXERCISE",
                "LABOUR",
                "LIFESTYLE",
                "RELATIONSHIPS",
                name="eduarticlecategory",
            ),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint(None, "edu_articles", type_="foreignkey")
    op.drop_column("edu_articles", "category_id")
    op.drop_table("edu_article_categories")
    # ### end Alembic commands ###
