"""Added 'mcr_no' to the 'doctor_account_creation_requests' table

Revision ID: 1c278de687c6
Revises: b61bc0f79da5
Create Date: 2026-01-18 19:31:52.241472

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1c278de687c6"
down_revision: Union[str, Sequence[str], None] = "b61bc0f79da5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("doctor_account_creation_requests", sa.Column("mcr_no", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("doctor_account_creation_requests", "mcr_no")
    # ### end Alembic commands ###
