"""Add 'is_deleted' field for threads and comments

Revision ID: 262a59fb6c76
Revises: 76f45b7f8e28
Create Date: 2026-01-28 12:37:45.946694

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "262a59fb6c76"
down_revision: Union[str, Sequence[str], None] = "76f45b7f8e28"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "community_threads", sa.Column("is_deleted", sa.Boolean(), server_default=sa.text("FALSE"), nullable=False)
    )
    op.alter_column("pregnant_women", "date_of_birth", existing_type=sa.DATE(), nullable=True)
    op.add_column(
        "thread_comments", sa.Column("is_deleted", sa.Boolean(), server_default=sa.text("FALSE"), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("thread_comments", "is_deleted")
    op.alter_column("pregnant_women", "date_of_birth", existing_type=sa.DATE(), nullable=False)
    op.drop_column("community_threads", "is_deleted")
    # ### end Alembic commands ###
