"""Generalize it so articles can be written by user

Revision ID: 28e167d7af10
Revises: ead783616502
Create Date: 2026-01-28 17:45:28.245956

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "28e167d7af10"
down_revision: Union[str, Sequence[str], None] = "ead783616502"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
