"""Added 'ingredients' field to Recipe table

Revision ID: 3b5356182b42
Revises: 409c46abfc56
Create Date: 2025-12-18 00:13:13.950276

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3b5356182b42"
down_revision: Union[str, Sequence[str], None] = "409c46abfc56"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Existing databases may already have rows in `recipes`. Adding a NOT NULL
    # column without a default will fail. Add it with a safe default/backfill,
    # then enforce NOT NULL.
    op.add_column(
        "recipes",
        sa.Column("ingredients", sa.String(), nullable=True, server_default=""),
    )
    op.execute("UPDATE recipes SET ingredients = '' WHERE ingredients IS NULL")
    op.alter_column("recipes", "ingredients", nullable=False, server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("recipes", "ingredients")
    # ### end Alembic commands ###
