"""Added 'ingredients' field to Recipe table

Revision ID: 3b5356182b42
Revises: 409c46abfc56
Create Date: 2025-12-18 00:13:13.950276

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3b5356182b42"
down_revision: Union[str, Sequence[str], None] = "409c46abfc56"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("recipes", sa.Column("ingredients", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("recipes", "ingredients")
    # ### end Alembic commands ###
