"""Tables or menstrual tracking, amend feedback and appointment

Revision ID: 5f114c8bd1d0
Revises: abe2d9d0bea1
Create Date: 2026-01-09 18:03:51.297071

"""

from typing import Sequence, Union

import fastapi_users_db_sqlalchemy
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5f114c8bd1d0"
down_revision: Union[str, Sequence[str], None] = "abe2d9d0bea1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "menstrual_periods",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("mother_id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.ForeignKeyConstraint(
            ["mother_id"],
            ["pregnant_women.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_menstrual_periods_start_date"), "menstrual_periods", ["start_date"], unique=False)
    op.add_column("appointments", sa.Column("chat_id", sa.UUID(), nullable=True))
    op.add_column("user_app_feedback", sa.Column("positive_score", sa.Float(), nullable=False))
    op.add_column("user_app_feedback", sa.Column("neutral_score", sa.Float(), nullable=False))
    op.add_column("user_app_feedback", sa.Column("negative_score", sa.Float(), nullable=False))
    op.add_column("user_app_feedback", sa.Column("compound_score", sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_app_feedback", "compound_score")
    op.drop_column("user_app_feedback", "negative_score")
    op.drop_column("user_app_feedback", "neutral_score")
    op.drop_column("user_app_feedback", "positive_score")
    op.drop_column("appointments", "chat_id")
    op.drop_index(op.f("ix_menstrual_periods_start_date"), table_name="menstrual_periods")
    op.drop_table("menstrual_periods")
    # ### end Alembic commands ###
