"""Refined table for 'expo push tokens'

Revision ID: 7024c39c2fac
Revises: fecf4f950054
Create Date: 2026-01-13 22:20:04.767688

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7024c39c2fac"
down_revision: Union[str, Sequence[str], None] = "fecf4f950054"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("expo_push_tokens", sa.Column("id", sa.Integer(), nullable=False))
    op.create_index(op.f("ix_expo_push_tokens_user_id"), "expo_push_tokens", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_expo_push_tokens_user_id"), table_name="expo_push_tokens")
    op.drop_column("expo_push_tokens", "id")
    # ### end Alembic commands ###
