"""Added 'specialisation' to 'doctor_account_creation_requests'

Revision ID: 76f45b7f8e28
Revises: 1c278de687c6
Create Date: 2026-01-18 20:02:25.487988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '76f45b7f8e28'
down_revision: Union[str, Sequence[str], None] = '1c278de687c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('doctor_account_creation_requests', sa.Column('specialisation', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctor_account_creation_requests', 'specialisation')
    # ### end Alembic commands ###
