"""Cascade behaviour for 'saved_edu_articles', upon deleting 'edu_articles'

Revision ID: 7bbcb25faecf
Revises: b8b12cf07f94
Create Date: 2026-01-29 16:57:03.036415

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7bbcb25faecf"
down_revision: Union[str, Sequence[str], None] = "b8b12cf07f94"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("saved_edu_articles_article_id_fkey"), "saved_edu_articles", type_="foreignkey")
    op.create_foreign_key(None, "saved_edu_articles", "edu_articles", ["article_id"], ["id"], ondelete="CASCADE")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "saved_edu_articles", type_="foreignkey")
    op.create_foreign_key(
        op.f("saved_edu_articles_article_id_fkey"), "saved_edu_articles", "edu_articles", ["article_id"], ["id"]
    )
    # ### end Alembic commands ###
