"""Added 'listed_at' field to 'products' table

Revision ID: 7ce638f0ddd7
Revises: 9462a8355581
Create Date: 2025-12-29 17:44:31.068457

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7ce638f0ddd7"
down_revision: Union[str, Sequence[str], None] = "9462a8355581"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products", sa.Column("listed_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("products", "listed_at")
    # ### end Alembic commands ###
