"""Added 'created_at' to 'edu_articles'

Revision ID: 9fd820d6be70
Revises: 28e167d7af10
Create Date: 2026-01-28 19:18:39.017660

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9fd820d6be70"
down_revision: Union[str, Sequence[str], None] = "28e167d7af10"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "edu_articles",
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("edu_articles", "created_at")
    # ### end Alembic commands ###
