"""Drop unique constraint for 'products' name

Revision ID: ab1433321f78
Revises: f3560af97a0b
Create Date: 2026-02-06 15:49:32.770579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'ab1433321f78'
down_revision: Union[str, Sequence[str], None] = 'f3560af97a0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('products_name_key'), 'products', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('products_name_key'), 'products', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
