"""Add trimester info to 'recipes', 'recipe_drafts', & 'edu_articles'

Revision ID: abe2d9d0bea1
Revises: 12350cae9e97
Create Date: 2026-01-09 02:48:42.600121

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "abe2d9d0bea1"
down_revision: Union[str, Sequence[str], None] = "12350cae9e97"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("edu_articles", sa.Column("trimester", sa.Integer(), nullable=False))
    op.add_column("recipe_drafts", sa.Column("trimester", sa.Integer(), nullable=True))
    op.add_column("recipes", sa.Column("trimester", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("recipes", "trimester")
    op.drop_column("recipe_drafts", "trimester")
    op.drop_column("edu_articles", "trimester")
    # ### end Alembic commands ###
