"""Each thread has exactly ONE category

Revision ID: b13f69c34738
Revises: 262a59fb6c76
Create Date: 2026-01-28 13:18:15.328409

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b13f69c34738"
down_revision: Union[str, Sequence[str], None] = "262a59fb6c76"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("thread_category_associations")
    op.add_column("community_threads", sa.Column("category_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "community_threads", "thread_categories", ["category_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "community_threads", type_="foreignkey")
    op.drop_column("community_threads", "category_id")
    op.create_table(
        "thread_category_associations",
        sa.Column("thread_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("category_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"], ["thread_categories.id"], name=op.f("thread_category_associations_category_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["thread_id"], ["community_threads.id"], name=op.f("thread_category_associations_thread_id_fkey")
        ),
        sa.PrimaryKeyConstraint("thread_id", "category_id", name=op.f("thread_category_associations_pkey")),
    )
    # ### end Alembic commands ###
