"""Further 'expo_push_tokens' table refinement

Revision ID: b61bc0f79da5
Revises: 7024c39c2fac
Create Date: 2026-01-17 00:15:21.534735

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b61bc0f79da5"
down_revision: Union[str, Sequence[str], None] = "7024c39c2fac"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("expo_push_tokens", "id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("expo_push_tokens", sa.Column("id", sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
