"""Remove 'img_key' for the edu_articles

Revision ID: b8549ecbd155
Revises: 9fd820d6be70
Create Date: 2026-01-28 19:37:41.425939

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b8549ecbd155"
down_revision: Union[str, Sequence[str], None] = "9fd820d6be70"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("edu_articles", "img_key")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("edu_articles", sa.Column("img_key", sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
