"""Added table to save GrapeJS data

Revision ID: c6cb6be254e2
Revises: b888f9e3a7a8
Create Date: 2025-12-16 21:18:34.300033

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "c6cb6be254e2"
down_revision: Union[str, Sequence[str], None] = "b888f9e3a7a8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
