"""Add new 'MERCHANT' value to the 'UserRole' enum

Revision ID: caaf822d6cdd
Revises: 7ce638f0ddd7
Create Date: 2025-12-29 20:36:28.414221

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "caaf822d6cdd"
down_revision: Union[str, Sequence[str], None] = "7ce638f0ddd7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add 'MERCHANT' value to UserRole enum
    op.execute("ALTER TYPE userrole ADD VALUE 'MERCHANT'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: PostgreSQL does not support removing enum values directly.
    # To downgrade, you would need to:
    # 1. Create a new enum without 'MERCHANT'
    # 2. Alter all columns using the old enum to use the new enum
    # 3. Drop the old enum
    # 4. Rename the new enum to the old name
    # This is complex and risky, so we're leaving it as a no-op.
    # Ensure no data uses 'MERCHANT' before attempting a manual downgrade.
    # ### end Alembic commands ###
