"""Draft tables for 'recipes' and 'products'

Revision ID: dc3da44083d0
Revises: 0d59fb754647
Create Date: 2026-01-03 17:08:22.046008

"""

from typing import Sequence, Union

import fastapi_users_db_sqlalchemy
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dc3da44083d0"
down_revision: Union[str, Sequence[str], None] = "0d59fb754647"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product_drafts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("merchant_id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("price_cents", sa.Integer(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("img_key", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["product_categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"],
            ["merchants.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "recipe_drafts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("nutritionist_id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("est_calories", sa.String(), nullable=True),
        sa.Column("pregnancy_benefit", sa.String(), nullable=True),
        sa.Column("img_key", sa.String(), nullable=True),
        sa.Column("serving_count", sa.Integer(), nullable=True),
        sa.Column("ingredients", sa.String(), nullable=True),
        sa.Column("instructions_markdown", sa.String(), nullable=True),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["recipe_categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["nutritionist_id"],
            ["nutritionists.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column(
        "recipes", sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("recipes", "created_at")
    op.drop_table("recipe_drafts")
    op.drop_table("product_drafts")
    # ### end Alembic commands ###
