"""EduArticles can be authored by either a 'doctor' or 'nutritionist'

Revision ID: ead783616502
Revises: b13f69c34738
Create Date: 2026-01-28 17:22:15.006344

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ead783616502"
down_revision: Union[str, Sequence[str], None] = "b13f69c34738"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("edu_articles_author_id_fkey"), "edu_articles", type_="foreignkey")
    op.create_foreign_key(None, "edu_articles", "users", ["author_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "edu_articles", type_="foreignkey")
    op.create_foreign_key(
        op.f("edu_articles_author_id_fkey"), "edu_articles", "volunteer_doctors", ["author_id"], ["id"]
    )
    # ### end Alembic commands ###
