"""Added 'doctor_specialisations' table, relevant FK for doctors

Revision ID: f19e156017a8
Revises: dc3da44083d0
Create Date: 2026-01-09 01:28:28.483460

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f19e156017a8"
down_revision: Union[str, Sequence[str], None] = "dc3da44083d0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "doctor_specialisations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("specialisation", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("specialisation"),
    )
    op.add_column("volunteer_doctors", sa.Column("specialisation_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "volunteer_doctors", "doctor_specialisations", ["specialisation_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "volunteer_doctors", type_="foreignkey")
    op.drop_column("volunteer_doctors", "specialisation_id")
    op.drop_table("doctor_specialisations")
    # ### end Alembic commands ###
